project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: https://roman-de-santos.github.io/E155Project/
        text: Project
      
      - href: labs.qmd
        text: Labs

      - href: resources.qmd
        text: Resources


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



